export const GET_TODO_LIST='GET_TODO_LIST'
export const GET_TODO_LIST_SUCCESS='GET_TODO_LIST_SUCCESS'
export const GET_TODO_LIST_FAILURE='GET_TODO_LIST_FAILURE'

export const SHOW_ADD_TODO_MODAL='SHOW_ADD_TODO_MODAL'

export const ADD_NEW_TODO_ITEM='ADD_NEW_TODO_ITEM'

export const SEARCH_FOR_ITEMS='SEARCH_FOR_ITEMS'

export const TOGGLE_TODO_DONE_CHECKBOX='TOGGLE_TODO_DONE_CHECKBOX'